# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


light_beer = Alcohol.create(name: 'light beer', calories: 103, drink_type: 'beer') 
regular_beer = Alcohol.create(name: 'regular beer', calories: 153, drink_type: 'beer')

wine_red = Alcohol.create(name: 'red wine', calories: 125, drink_type: 'wine') 
wine_white = Alcohol.create(name: 'white wine',calories: 122, drink_type: 'wine')
wine_table = Alcohol.create(name: 'table wine', calories: 124, drink_type: 'wine') 
wine_sangria = Alcohol.create(name: 'sangria', calories: 173, drink_type: 'wine')
wine_champagne = Alcohol.create(name: 'champagne', calories: 87, drink_type: 'wine')

spirit_bourbon = Alcohol.create(name: 'bourbon', calories: 105, drink_type: 'spirit')
spirit_brandy = Alcohol.create(name: 'brandy', calories: 96, drink_type: 'spirit')
spirit_gin = Alcohol.create(name: 'gin', calories: 110, drink_type: 'spirit')
spirit_rum = Alcohol.create(name: 'rum',calories: 97, drink_type: 'spirit')
spirit_tequila = Alcohol.create(name: 'tequila', calories: 97, drink_type: 'spirit')
spirit_vodka = Alcohol.create(name: 'vodka', calories: 97, drink_type: 'spirit')
spirit_whiskey = Alcohol.create(name: 'whiskey', calories: 105, drink_type: 'spirit')

mixed_gin_and_tonic = Alcohol.create(name: 'gin and tonic', calories: 171, drink_type: 'mixed')
mixed_rum_and_cola = Alcohol.create(name: 'rum and cola', calories: 154, drink_type: 'mixed')
mixed_bloody_mary = Alcohol.create(name: 'bloody mary', calories: 123, drink_type: 'mixed')
mixed_caipirinha = Alcohol.create(name: 'caipirinha', calories: 263, drink_type: 'mixed')
mixed_cape_cod = Alcohol.create(name: 'cape cod', calories: 148, drink_type: 'mixed')
mixed_dairquiri = Alcohol.create(name: 'daiquiri', calories: 113, drink_type: 'mixed')
mixed_grasshopper = Alcohol.create(name: 'grasshopper', calories: 164, drink_type: 'mixed')
mixed_high_ball = Alcohol.create(name: 'high ball', calories: 104, drink_type: 'mixed')
mixed_kamikaze = Alcohol.create(name: 'kamikaze', calories: 178, drink_type: 'mixed')
mixed_long_island = Alcohol.create(name: 'long island ice tea', calories: 138, drink_type: 'mixed')
mixed_mai_tai = Alcohol.create(name: 'mai tai', calories: 309, drink_type: 'mixed')
mixed_manahattan = Alcohol.create(name: 'manahattan', calories: 129, drink_type: 'mixed')
mixed_margarita = Alcohol.create(name: 'margarita', calories: 168, drink_type: 'mixed')
mixed_martini = Alcohol.create(name: 'martini', calories: 160, drink_type: 'mixed')
mixed_mint_julep = Alcohol.create(name: 'mint julep', calories: 156, drink_type: 'mixed')
mixed_mojito = Alcohol.create(name: 'mojito', calories: 217, drink_type: 'mixed')
mixed_sea_breeze = Alcohol.create(name: 'sea breeze', calories: 177, drink_type: 'mixed')
mixed_srew_driver = Alcohol.create(name: 'screw driver', calories: 181, drink_type: 'mixed')
mixed_tequilla = Alcohol.create(name: 'tequilla sunrise', calories: 189, drink_type: 'mixed')



# Acitivities 
standing = Activity.create(name: 'standing', calories: 147)
reading = Activity.create(name: 'reading', calories: 147)
sex = Activity.create(name: 'sexual activity', calories: 147)
sewing = Activity.create(name: 'sewing', calories: 147)
driving = Activity.create(name: 'driving', calories: 118)
studying = Activity.create(name: 'studying', calories: 147)
golf_with_cart = Activity.create(name: 'golfing with cart', calories: 147)
karokee = Activity.create(name: 'karokee', calories: 147)
recieving_massage = Activity.create(name: 'recieving massage', calories: 147)
walking_slowly = Activity.create(name: 'walking (2.0 mph)', calories: 147)
breastfeeding = Activity.create(name: 'breastfeeding', calories: 147)
cooking = Activity.create(name: 'cooking', calories: 147)
washing_dishes = Activity.create(name: 'washing dishes', calories: 220)
yoga = Activity.create(name: 'yoga', calories: 220)
grocery_shopping = Activity.create(name: 'grocery shopping', calories: 220)
vacuuming = Activity.create(name: 'vacuuming', calories: 220)
boating = Activity.create(name: 'boating', calories: 220)
surfing = Activity.create(name: 'surfing', calories: 220)
sailing = Activity.create(name: 'sailing', calories: 220)
stretching = Activity.create(name: 'stretching', calories: 184)
fishing = Activity.create(name: 'fishing', calories: 220)
pilates = Activity.create(name: 'pilates', calories: 228)

# medium intensity 
walking_3 = Activity.create(name: 'walking (3.0 mph)', calories: 243)
hot_yoga = Activity.create(name: 'hot yoga', calories: 294)
horseback_riding = Activity.create(name: 'horseback riding', calories: 294)
yard_work = Activity.create(name: 'yard work', calories: 294)
table_tenis = Activity.create(name: 'table tenis', calories: 294)
golf_walking = Activity.create(name: 'golf (walking)', calories: 294)
slow_dancing = Activity.create(name: 'slow dancing', calories: 294)
bicyling = Activity.create(name: 'bicyling (<10mph)', calories: 294)
mowing = Activity.create(name: 'mowing the lawn', calories: 368)
shoveling = Activity.create(name: 'shoveling (snow)', calories: 368)
walking = Activity.create(name: 'walking (4.0 mph)', calories: 368)
cricket = Activity.create(name: 'cricket', calories: 368)
baseball = Activity.create(name: 'baseball', calories: 368)
softball = Activity.create(name: 'softball', calories: 368)
badmitten = Activity.create(name: 'badmitten', calories: 368)
square_dancing = Activity.create(name: 'square dancing', calories: 368)
hula_hoop = Activity.create(name: 'hula hoop', calories: 368)
kayaking = Activity.create(name: 'kayaking', calories: 368)
hunting = Activity.create(name: 'hunting', calories: 368)
skating = Activity.create(name: 'skating (10 mph)', calories: 368)

biking_11 = Activity.create(name: 'biking (11 mph)', calories: 441)
basketball = Activity.create(name: 'basketball', calories: 441)
hiking = Activity.create(name: 'hiking', calories: 441)
skating = Activity.create(name: 'weight training (moderate)', calories: 441)
skating = Activity.create(name: 'pole dancing', calories: 441)
walking_5 = Activity.create(name: 'walking (5 mph)', calories: 441)
scuba_diving = Activity.create(name: 'scuba diving', calories: 441)
fast_dancing = Activity.create(name: 'fast step dancing', calories: 441)

stair_climbing = Activity.create(name: 'climbing stairs', calories: 514)
HIIT = Activity.create(name: 'HIIT', calories: 514)
jiu_jitsu = Activity.create(name: 'jiu jitsu', calories: 514)
insanity = Activity.create(name: 'insanity', calories: 514)
tai_bo = Activity.create(name: 'tai bo', calories: 514)
tae_kwon_do = Activity.create(name: 'tae kwon do', calories: 514)
martial_arts_general = Activity.create(name: 'other martial arts', calories: 514)
moderate_swiming = Activity.create(name: 'moderate swimming', calories: 514)
swimming = Activity.create(name: 'moderate swimming', calories: 514)
p90 = Activity.create(name: 'p90x', calories: 514)
snow_boarding = Activity.create(name: 'snow boarding', calories: 514)
body_pump = Activity.create(name: 'body pump', calories: 514)
balet = Activity.create(name: 'balet', calories: 514)
curves = Activity.create(name: 'curves', calories: 514)
cross_fit = Activity.create(name: 'cross-fit', calories: 514)
trx = Activity.create(name: 'trx', calories: 514)
general_cardio = Activity.create(name: 'general cardio', calories: 514)
rowing = Activity.create(name: 'rowing', calories: 588)
skiing = Activity.create(name: 'skiing', calories: 588)
rock_climbing = Activity.create(name: 'rock climbing', calories: 588)
jogging = Activity.create(name: 'jogging (5.0 mph)', calories: 588)
squating = Activity.create(name: 'squating', calories: 588)
tennis = Activity.create(name: 'tennis', calories: 588)
soccer = Activity.create(name: 'soccer', calories: 588)
weight_training = Activity.create(name: 'weight training', calories: 588)
body_building = Activity.create(name: 'body building', calories: 588)
spin_class = Activity.create(name: 'spin class', calories: 588)
vibrating_platform = Activity.create(name: 'vibrating platform', calories: 588)
football = Activity.create(name: 'football', calories: 588)
hockey = Activity.create(name: 'hockey', calories: 588)
biking_13 = Activity.create(name: 'biking (13 mph)', calories: 588)
eliptical = Activity.create(name: 'eliptical', calories: 588)
ice_hockey = Activity.create(name: 'ice hockey', calories: 588)
mountain_biking = Activity.create(name: 'mountain biking', calories: 588)

running_6 = Activity.create(name: 'running (6 mph)', calories: 735)
biking_15 = Activity.create(name: 'biking (15 mph)', calories: 735)
fast_swimming = Activity.create(name: 'fast swimming', calories: 735)
jumping_rope = Activity.create(name: 'jumping rope', calories: 735)
running_7 = Activity.create(name: 'running (7 mph)', calories: 845)
cc_skining = Activity.create(name: 'cross-country skiiing (7 mph)', calories: 882)
biking_17 = Activity.create(name: 'biking (17.5 mph)', calories: 882)
running_8 = Activity.create(name: 'running (8 mph)', calories: 992)
running_9 = Activity.create(name: 'running (9 mph)', calories: 1102)
running_10 = Activity.create(name: 'running (10 mph)', calories: 1176)

